export const CATEGORY = {
  TECHNOLOGY: 'technology',
  TRAVEL: 'travel',
  FOOD: 'food',
  HEALTH_AND_FITNESS: 'health_and_fitness',
  FASHION: 'fashion',
  LIFESTYLE: 'lifestyle',
  PERSONAL_DEVELOPMENT: 'personal_development',
  PARENTING: 'parenting',
  FINANCE_AND_MONEY: 'finance_and_money',
  SPORTS: 'sports',
  ENTERTAINMENT: 'entertainment',
  BOOKS_AND_LITERATURE: 'books_and_literature',
  EDUCATION: 'education',
  SCIENCE_AND_NATURE: 'science_and_nature',
  DIY_AND_CRAFTS: 'diy_and_crafts',
  HOME_AND_DECOR: 'home_and_decor',
  PHOTOGRAPHY: 'photography',
  GAMING: 'gaming',
  MUSIC: 'music',
  ART_AND_DESIGN: 'art_and_design',
  CAREER_AND_WORK: 'career_and_work',
  RELATIONSHIPS: 'relationships',
  NATURE_AND_ENVIRONMENT: 'nature_and_environment',
  INSPIRATIONAL: 'inspirational',
  HUMOR: 'humor',
  HISTORY: 'history',
  POLITICS_AND_SOCIAL_ISSUES: 'politics_and_social_issues',
  RELIGION_AND_SPIRITUALITY: 'religion_and_spirituality',
  SELF_CARE_AND_WELLNESS: 'self_care_and_wellness',
  MENTAL_HEALTH: 'mental_health',
};

export const TAG = {
  TECHNOLOGY: 'technology',
  TRAVEL: 'travel',
  FOOD: 'food',
  HEALTH: 'health',
  FITNESS: 'fitness',
  FASHION: 'fashion',
  BEAUTY: 'beauty',
  SELF_IMPROVEMENT: 'self_improvement',
  PARENTING: 'parenting',
  FINANCE: 'finance',
  SPORTS: 'sports',
  MOVIES: 'movies',
  MUSIC: 'music',
  BOOKS: 'books',
  EDUCATION: 'education',
  SCIENCE: 'science',
  DIY: 'diy',
  HOME_DECOR: 'home_decor',
  PHOTOGRAPHY: 'photography',
  GAMING: 'gaming',
  ART: 'art',
  CAREER: 'career',
  RELATIONSHIPS: 'relationships',
  ENVIRONMENT: 'environment',
  INSPIRATION: 'inspiration',
  HUMOR: 'humor',
  HISTORY: 'history',
  POLITICS: 'politics',
  RELIGION: 'religion',
  MEDITATION: 'meditation',
  MINDFULNESS: 'mindfulness',
};

export const STATUS = {
  DRAFT: 'draft',
  PUBLISH: 'publish',
  ARCHIVE: 'archive',
};

export const POST_SORT_BY = {
  newest: '-createdAt',
  oldest: 'createdAt',
  'a-z': 'title',
  'z-a': '-title',
};
